kind: pipeline
type: docker

name: publish

steps:
- name: build
  image: plugins/docker
  settings:
    repo: ghcr.io/datahearth/ddnsclient
    registry: ghcr.io
    username:
      from_secret: ghcr_username
    password:
      from_secret: ghcr_password
    auto_tag: true

---

kind: pipeline
type: docker

name: build-and-test

steps:
- name: build-testing-pr
  image: golang
  commands:
  - go build ./cmd/main.go
  - go test
  when:
    event:
    - pull_request

- name: build-testing-master
  image: golang
  commands:
  - go build ./cmd/main.go
  - go test
  when:
    branch:
    - master
    event:
    - push
